### PR TITLE
Renamed appleseed module to appleseed_maya.

### PR DESCRIPTION
**Pull request by est77**
Avoid conflitcs with appleseed.python, if we (or users) want to use it in the future.

### CODE REVIEW

**Comment by haggi** [comment]
Oh, yes. Good idea. The module (appleseed-maya.mod) file has to be changed as well.

**Comment by est77** [comment]
Fixed

**Comment by haggi** [comment]
Thanks.

**Comment by est77** [comment]
Is it ok to merge this?
You closed it without merging.

**Comment by haggi** [comment]
Upps, sorry. I hit the wrong button.

**Pull request merged**
