### PR TITLE
Update docs to reflect shader changes

### PR DESCRIPTION
**Pull request by luisbarrancos**
addressed in https://github.com/appleseedhq/appleseed/issues/2688 and https://github.com/appleseedhq/appleseed/issues/2680.
Minor formatting fixes and bibtex entries fixes.

### CODE REVIEW

**Review by dictoon — APPROVED** [review]
Thanks!

You replaced links to PNG images by links to JPG images but you haven't converted the images, do images already exist in JPG format?

**Comment by luisbarrancos** [comment]
@dictoon the Matte screenshots were JPG, so that is correct, with matching screenshots in master. Perhaps we should just convert everything to JPG at some point to save some storage.

**Comment by dictoon** [comment]
Storage is really not a worry. Loading times maybe are, but in the context of a renderer it seems to me that artifact-free images is an advantage worth paying for.

**Comment by dictoon** [comment]
@luisbarrancos Shall we merge this and replace JPEG images by PNG ones in a later PR?

**Pull request merged**
