### PR TITLE
Expose noise seed render controls

### PR DESCRIPTION
**Pull request by Mango-3**
- Add sampling noise pattern variation per frame
- Optionally, allow disabling it (Lock Sampling Pattern)

### CODE REVIEW

**Comment by est77** [comment]
I would prefer that we do this automatically, without any controls.
Simply set the seed to frame.
I cannot imagine any reason why someone would like to render an anim with a static noise pattern

**Comment by Mango-3** [comment]
Modified the PR so that only the `Lock Sampling Pattern`checkbox is exposed
(see screenshot).
By default the noise seed is varied per frame unless the checkbox is activated by the user.
capture

**Comment by luisbarrancos** [comment]
As discussed earlier, the seed is actually useful in for instance, the Houdini case (for Altus denoiser). We can expose it as *sampling pattern seed* or *sampling seed*. Just a reminder in order not to let that forum discussion slip by into unintentional oblivion.

**Comment by Mango-3** [comment]
I put back the explicit control for setting the seed (it was in the initial commit of the PR but then Esteban wanted it removed and I took it out)

**Review by est77 — APPROVED** [review]

**Pull request merged**
